### ISSUE TITLE
How to compile for windows in linux?

### ISSUE THREAD

**Issue by urdarinda** [fireworm71/veriumMiner#5]
I have mingw64 installed in linux

**Comment by fireworm71** [comment]
I believe you need to pass in `--target-platform=x86_x64-.....` (the mingw stuff goes there).  Note you also need to cross compile OpenSSL, and the other dependencies...

I'll update the windows instructions to build _on windows_.

**Comment by urdarinda** [comment]
Cross compiling OpenSSL is a pain. I guess I'll just use the provided binary file since its updated .
Thanks
