### ISSUE TITLE
Memory usage on arm7 (orange-pi)

### ISSUE THREAD

**Issue by jaapschellekens** [fireworm71/veriumMiner#8]
Compared to https://github.com/VeriumReserve/veriumMiner the memory usage on a orange pi (arm7) is increased a lot. Can only run one thread now while the original miner can run 4 threads on a pi.

**Comment by wifiguru10** [comment]
try adding "-1 4" after cpuminer, that'll do four 1-way threads

**Comment by jaapschellekens** [comment]
Thanks, that worked fine!
